---
include:
  - board: keypoint_dongle
    shield: st7789_display
  - board: keypoint_dongle_left
    shield: lpm_view;left_bbtrackpad_keypoint
  - board: keypoint_dongle_right
    shield: lpm_view;right_trackpoint_keypoint

# reset firmware
  - board: keypoint_dongle
    shield: st7789_display;settings_reset
  - board: keypoint_dongle_left
    shield: lpm_view;left_bbtrackpad_keypoint;settings_reset
  - board: keypoint_dongle_right
    shield: lpm_view;right_trackpoint_keypoint;settings_reset
